using System.Collections.Generic;

namespace WordProSuite.Desktop.Commands
{
    internal sealed class FeatureReference
    {
        internal FeatureReference(int number, string engine, string commandId)
        { Number = number; Engine = engine; CommandId = commandId; }
        internal int Number { get; }
        internal string Engine { get; }
        internal string CommandId { get; }
    }

    internal static class FeatureReferenceCatalog
    {
        internal static readonly IReadOnlyList<FeatureReference> All = new[]
        {
            new FeatureReference(1, "إدارة التبويبات والمستندات الذكية", "workspace-save-session"),
            new FeatureReference(2, "إدارة التبويبات والمستندات الذكية", "workspace-export-open-docs"),
            new FeatureReference(3, "إدارة التبويبات والمستندات الذكية", "workspace-rename-document"),
            new FeatureReference(4, "إدارة التبويبات والمستندات الذكية", "workspace-restore-session"),
            new FeatureReference(5, "إدارة التبويبات والمستندات الذكية", "workspace-close-others"),
            new FeatureReference(6, "إدارة التبويبات والمستندات الذكية", "workspace-close-unmodified"),
            new FeatureReference(7, "إدارة التبويبات والمستندات الذكية", "workspace-split-toggle"),
            new FeatureReference(8, "إدارة التبويبات والمستندات الذكية", "workspace-compare-file"),
            new FeatureReference(9, "إدارة التبويبات والمستندات الذكية", "workspace-duplicate-document"),
            new FeatureReference(10, "إدارة التبويبات والمستندات الذكية", "workspace-arrange-windows"),
            new FeatureReference(11, "إدارة التبويبات والمستندات الذكية", "insert-document-path"),
            new FeatureReference(12, "إدارة التبويبات والمستندات الذكية", "insert-confidential-banner"),
            new FeatureReference(13, "إدارة التبويبات والمستندات الذكية", "insert-document-name"),
            new FeatureReference(14, "إدارة التبويبات والمستندات الذكية", "insert-current-datetime"),
            new FeatureReference(15, "إدارة التبويبات والمستندات الذكية", "insert-page-break-pro"),
            new FeatureReference(16, "إدارة التبويبات والمستندات الذكية", "insert-section-next-page"),
            new FeatureReference(17, "إدارة التبويبات والمستندات الذكية", "zoom-100-pro"),
            new FeatureReference(18, "إدارة التبويبات والمستندات الذكية", "zoom-110-pro"),
            new FeatureReference(19, "إدارة التبويبات والمستندات الذكية", "zoom-125-pro"),
            new FeatureReference(20, "إدارة التبويبات والمستندات الذكية", "zoom-150-pro"),
            new FeatureReference(21, "إدارة التبويبات والمستندات الذكية", "zoom-75-pro"),
            new FeatureReference(22, "إدارة التبويبات والمستندات الذكية", "zoom-85-pro"),
            new FeatureReference(23, "إدارة التبويبات والمستندات الذكية", "formatting-marks-off"),
            new FeatureReference(24, "إدارة التبويبات والمستندات الذكية", "formatting-marks-on"),
            new FeatureReference(25, "إدارة التبويبات والمستندات الذكية", "rulers-off"),
            new FeatureReference(26, "إدارة التبويبات والمستندات الذكية", "rulers-on"),
            new FeatureReference(27, "إدارة التبويبات والمستندات الذكية", "view-normal-pro"),
            new FeatureReference(28, "إدارة التبويبات والمستندات الذكية", "view-outline-pro"),
            new FeatureReference(29, "إدارة التبويبات والمستندات الذكية", "view-print-pro"),
            new FeatureReference(30, "إدارة التبويبات والمستندات الذكية", "view-reading-pro"),
            new FeatureReference(31, "إدارة التبويبات والمستندات الذكية", "view-web-pro"),
            new FeatureReference(32, "إدارة التبويبات والمستندات الذكية", "document-statistics"),
            new FeatureReference(33, "إدارة التبويبات والمستندات الذكية", "insert-cover"),
            new FeatureReference(34, "إدارة التبويبات والمستندات الذكية", "insert-file-name"),
            new FeatureReference(35, "إدارة التبويبات والمستندات الذكية", "list-fonts"),
            new FeatureReference(36, "إدارة التبويبات والمستندات الذكية", "replace-font"),
            new FeatureReference(37, "إدارة التبويبات والمستندات الذكية", "clear-headers-footers"),
            new FeatureReference(38, "إدارة التبويبات والمستندات الذكية", "columns-1"),
            new FeatureReference(39, "إدارة التبويبات والمستندات الذكية", "columns-2"),
            new FeatureReference(40, "إدارة التبويبات والمستندات الذكية", "columns-3"),
            new FeatureReference(41, "معالجة وتنظيف النصوص الشاملة", "text-comma-to-lines"),
            new FeatureReference(42, "معالجة وتنظيف النصوص الشاملة", "text-list-to-plain"),
            new FeatureReference(43, "معالجة وتنظيف النصوص الشاملة", "text-normalize-tabs"),
            new FeatureReference(44, "معالجة وتنظيف النصوص الشاملة", "text-remove-email-quotes"),
            new FeatureReference(45, "معالجة وتنظيف النصوص الشاملة", "text-remove-extra-breaks"),
            new FeatureReference(46, "معالجة وتنظيف النصوص الشاملة", "text-trim-document"),
            new FeatureReference(47, "معالجة وتنظيف النصوص الشاملة", "text-semicolon-to-paragraph"),
            new FeatureReference(48, "معالجة وتنظيف النصوص الشاملة", "text-punctuation-spacing"),
            new FeatureReference(49, "معالجة وتنظيف النصوص الشاملة", "linebreaks-to-paragraphs"),
            new FeatureReference(50, "معالجة وتنظيف النصوص الشاملة", "collapse-spaces"),
            new FeatureReference(51, "معالجة وتنظيف النصوص الشاملة", "join-paragraphs"),
            new FeatureReference(52, "معالجة وتنظيف النصوص الشاملة", "prefix-lines"),
            new FeatureReference(53, "معالجة وتنظيف النصوص الشاملة", "suffix-lines"),
            new FeatureReference(54, "معالجة وتنظيف النصوص الشاملة", "extract-emails"),
            new FeatureReference(55, "معالجة وتنظيف النصوص الشاملة", "extract-urls"),
            new FeatureReference(56, "معالجة وتنظيف النصوص الشاملة", "lowercase"),
            new FeatureReference(57, "معالجة وتنظيف النصوص الشاملة", "paragraphs-bullets"),
            new FeatureReference(58, "معالجة وتنظيف النصوص الشاملة", "paragraphs-numbers"),
            new FeatureReference(59, "معالجة وتنظيف النصوص الشاملة", "paste-plain"),
            new FeatureReference(60, "معالجة وتنظيف النصوص الشاملة", "remove-duplicate-lines"),
            new FeatureReference(61, "معالجة وتنظيف النصوص الشاملة", "remove-duplicate-paragraphs"),
            new FeatureReference(62, "معالجة وتنظيف النصوص الشاملة", "remove-duplicate-words"),
            new FeatureReference(63, "معالجة وتنظيف النصوص الشاملة", "remove-hyperlinks"),
            new FeatureReference(64, "معالجة وتنظيف النصوص الشاملة", "smart-quotes"),
            new FeatureReference(65, "معالجة وتنظيف النصوص الشاملة", "sort-lines-asc"),
            new FeatureReference(66, "معالجة وتنظيف النصوص الشاملة", "sort-lines-desc"),
            new FeatureReference(67, "معالجة وتنظيف النصوص الشاملة", "text-statistics"),
            new FeatureReference(68, "معالجة وتنظيف النصوص الشاملة", "trim-lines"),
            new FeatureReference(69, "معالجة وتنظيف النصوص الشاملة", "uppercase"),
            new FeatureReference(70, "معالجة وتنظيف النصوص الشاملة", "clear-list"),
            new FeatureReference(71, "معالجة وتنظيف النصوص الشاملة", "duplicate-selection"),
            new FeatureReference(72, "معالجة وتنظيف النصوص الشاملة", "extract-phones"),
            new FeatureReference(73, "معالجة وتنظيف النصوص الشاملة", "invert-case"),
            new FeatureReference(74, "معالجة وتنظيف النصوص الشاملة", "normalize-dashes"),
            new FeatureReference(75, "معالجة وتنظيف النصوص الشاملة", "remove-empty-paragraphs"),
            new FeatureReference(76, "معالجة وتنظيف النصوص الشاملة", "remove-leading-spaces"),
            new FeatureReference(77, "معالجة وتنظيف النصوص الشاملة", "remove-nonprinting"),
            new FeatureReference(78, "معالجة وتنظيف النصوص الشاملة", "remove-trailing-spaces"),
            new FeatureReference(79, "معالجة وتنظيف النصوص الشاملة", "sentence-case"),
            new FeatureReference(80, "معالجة وتنظيف النصوص الشاملة", "split-by-delimiter"),
            new FeatureReference(81, "الهندسة اللغوية والخطوط العربية", "arabic-proofing"),
            new FeatureReference(82, "الهندسة اللغوية والخطوط العربية", "english-proofing"),
            new FeatureReference(83, "الهندسة اللغوية والخطوط العربية", "arabic-decimal-separator"),
            new FeatureReference(84, "الهندسة اللغوية والخطوط العربية", "arabic-normalize-ligatures"),
            new FeatureReference(85, "الهندسة اللغوية والخطوط العربية", "arabic-thousands-separator"),
            new FeatureReference(86, "الهندسة اللغوية والخطوط العربية", "arabic-remove-quranic-marks"),
            new FeatureReference(87, "الهندسة اللغوية والخطوط العربية", "auto-direction"),
            new FeatureReference(88, "الهندسة اللغوية والخطوط العربية", "arabic-clean-all"),
            new FeatureReference(89, "الهندسة اللغوية والخطوط العربية", "normalize-arabic-punctuation"),
            new FeatureReference(90, "الهندسة اللغوية والخطوط العربية", "rtl"),
            new FeatureReference(91, "الهندسة اللغوية والخطوط العربية", "arabic-quotes"),
            new FeatureReference(92, "الهندسة اللغوية والخطوط العربية", "digits-eastern"),
            new FeatureReference(93, "الهندسة اللغوية والخطوط العربية", "digits-western"),
            new FeatureReference(94, "الهندسة اللغوية والخطوط العربية", "insert-arabic-date"),
            new FeatureReference(95, "الهندسة اللغوية والخطوط العربية", "keyboard-ar-to-en"),
            new FeatureReference(96, "الهندسة اللغوية والخطوط العربية", "keyboard-en-to-ar"),
            new FeatureReference(97, "الهندسة اللغوية والخطوط العربية", "ltr"),
            new FeatureReference(98, "الهندسة اللغوية والخطوط العربية", "normalize-arabic"),
            new FeatureReference(99, "الهندسة اللغوية والخطوط العربية", "number-arabic-words"),
            new FeatureReference(100, "الهندسة اللغوية والخطوط العربية", "persian-to-arabic-letters"),
            new FeatureReference(101, "الهندسة اللغوية والخطوط العربية", "remove-diacritics"),
            new FeatureReference(102, "الهندسة اللغوية والخطوط العربية", "wrap-arabic-brackets"),
            new FeatureReference(103, "الهندسة اللغوية والخطوط العربية", "digits-persian"),
            new FeatureReference(104, "الهندسة اللغوية والخطوط العربية", "insert-hijri-date"),
            new FeatureReference(105, "الهندسة اللغوية والخطوط العربية", "remove-tatweel"),
            new FeatureReference(106, "الهندسة اللغوية والخطوط العربية", "remove-zero-width"),
            new FeatureReference(107, "الهندسة اللغوية والخطوط العربية", "reverse-text"),
            new FeatureReference(108, "الهندسة اللغوية والخطوط العربية", "font-aptos-11"),
            new FeatureReference(109, "الهندسة اللغوية والخطوط العربية", "font-aptos-12"),
            new FeatureReference(110, "الهندسة اللغوية والخطوط العربية", "font-arial-10"),
            new FeatureReference(111, "الهندسة اللغوية والخطوط العربية", "font-arial-12"),
            new FeatureReference(112, "الهندسة اللغوية والخطوط العربية", "font-arial-16"),
            new FeatureReference(113, "الهندسة اللغوية والخطوط العربية", "font-calibri-10"),
            new FeatureReference(114, "الهندسة اللغوية والخطوط العربية", "font-calibri-12"),
            new FeatureReference(115, "الهندسة اللغوية والخطوط العربية", "font-cambria-12"),
            new FeatureReference(116, "الهندسة اللغوية والخطوط العربية", "font-century-gothic-11"),
            new FeatureReference(117, "الهندسة اللغوية والخطوط العربية", "font-consolas-10"),
            new FeatureReference(118, "الهندسة اللغوية والخطوط العربية", "font-courier-10"),
            new FeatureReference(119, "الهندسة اللغوية والخطوط العربية", "font-dubai-12"),
            new FeatureReference(120, "الهندسة اللغوية والخطوط العربية", "font-georgia-12"),
            new FeatureReference(121, "الهندسة اللغوية والخطوط العربية", "font-noto-naskh-14"),
            new FeatureReference(122, "الهندسة اللغوية والخطوط العربية", "font-segoe-10"),
            new FeatureReference(123, "الهندسة اللغوية والخطوط العربية", "font-segoe-12"),
            new FeatureReference(124, "الهندسة اللغوية والخطوط العربية", "font-simplified-arabic-14"),
            new FeatureReference(125, "الهندسة اللغوية والخطوط العربية", "font-tahoma-10"),
            new FeatureReference(126, "المساعد الذكي والذكاء الاصطناعي", "smart-executive-summary"),
            new FeatureReference(127, "المساعد الذكي والذكاء الاصطناعي", "smart-offline-summary"),
            new FeatureReference(128, "المساعد الذكي والذكاء الاصطناعي", "smart-sentiment"),
            new FeatureReference(129, "المساعد الذكي والذكاء الاصطناعي", "smart-keywords"),
            new FeatureReference(130, "المساعد الذكي والذكاء الاصطناعي", "smart-outline"),
            new FeatureReference(131, "المساعد الذكي والذكاء الاصطناعي", "smart-readability-advice"),
            new FeatureReference(132, "المساعد الذكي والذكاء الاصطناعي", "smart-title-suggestions"),
            new FeatureReference(133, "المساعد الذكي والذكاء الاصطناعي", "ai-chat-provider"),
            new FeatureReference(134, "المساعد الذكي والذكاء الاصطناعي", "ai-provider-settings"),
            new FeatureReference(135, "المساعد الذكي والذكاء الاصطناعي", "ai-rewrite-provider"),
            new FeatureReference(136, "المساعد الذكي والذكاء الاصطناعي", "ai-translate-provider"),
            new FeatureReference(137, "المساعد الذكي والذكاء الاصطناعي", "smart-action-items"),
            new FeatureReference(138, "المساعد الذكي والذكاء الاصطناعي", "smart-decisions"),
            new FeatureReference(139, "المساعد الذكي والذكاء الاصطناعي", "smart-reading-questions"),
            new FeatureReference(140, "المساعد الذكي والذكاء الاصطناعي", "calculator"),
            new FeatureReference(141, "المساعد الذكي والذكاء الاصطناعي", "insert-checklist"),
            new FeatureReference(142, "المساعد الذكي والذكاء الاصطناعي", "insert-guid"),
            new FeatureReference(143, "المساعد الذكي والذكاء الاصطناعي", "insert-lorem-arabic"),
            new FeatureReference(144, "المساعد الذكي والذكاء الاصطناعي", "metric-words-pro"),
            new FeatureReference(145, "المساعد الذكي والذكاء الاصطناعي", "open-log"),
            new FeatureReference(146, "المساعد الذكي والذكاء الاصطناعي", "metric-bookmarks-pro"),
            new FeatureReference(147, "المساعد الذكي والذكاء الاصطناعي", "metric-characters-pro"),
            new FeatureReference(148, "المساعد الذكي والذكاء الاصطناعي", "metric-comments-pro"),
            new FeatureReference(149, "المساعد الذكي والذكاء الاصطناعي", "metric-fields-pro"),
            new FeatureReference(150, "المساعد الذكي والذكاء الاصطناعي", "metric-footnotes-pro"),
            new FeatureReference(151, "المساعد الذكي والذكاء الاصطناعي", "metric-headings-pro"),
            new FeatureReference(152, "المساعد الذكي والذكاء الاصطناعي", "metric-hyperlinks-pro"),
            new FeatureReference(153, "المساعد الذكي والذكاء الاصطناعي", "metric-images-pro"),
            new FeatureReference(154, "المساعد الذكي والذكاء الاصطناعي", "metric-pages-pro"),
            new FeatureReference(155, "المساعد الذكي والذكاء الاصطناعي", "metric-paragraphs-pro"),
            new FeatureReference(156, "المساعد الذكي والذكاء الاصطناعي", "metric-readability-pro"),
            new FeatureReference(157, "المساعد الذكي والذكاء الاصطناعي", "metric-revisions-pro"),
            new FeatureReference(158, "المساعد الذكي والذكاء الاصطناعي", "metric-sections-pro"),
            new FeatureReference(159, "المساعد الذكي والذكاء الاصطناعي", "metric-tables-pro"),
            new FeatureReference(160, "المساعد الذكي والذكاء الاصطناعي", "document-dashboard"),
            new FeatureReference(161, "المساعد الذكي والذكاء الاصطناعي", "word-frequency-top"),
            new FeatureReference(162, "المساعد الذكي والذكاء الاصطناعي", "list-bookmarks"),
            new FeatureReference(163, "المساعد الذكي والذكاء الاصطناعي", "list-document-headings"),
            new FeatureReference(164, "المساعد الذكي والذكاء الاصطناعي", "word-frequency-report"),
            new FeatureReference(165, "المساعد الذكي والذكاء الاصطناعي", "long-paragraph-report"),
            new FeatureReference(166, "المساعد الذكي والذكاء الاصطناعي", "extract-numbers-pro"),
            new FeatureReference(167, "المساعد الذكي والذكاء الاصطناعي", "academic-heading-audit"),
            new FeatureReference(168, "المساعد الذكي والذكاء الاصطناعي", "insert-executive-summary"),
            new FeatureReference(169, "المساعد الذكي والذكاء الاصطناعي", "insert-pestle-matrix"),
            new FeatureReference(170, "المساعد الذكي والذكاء الاصطناعي", "insert-swot-matrix"),
            new FeatureReference(171, "المساعد الذكي والذكاء الاصطناعي", "insert-swot-matrix-v3"),
            new FeatureReference(172, "المساعد الذكي والذكاء الاصطناعي", "legal-highlight-obligations"),
            new FeatureReference(173, "المساعد الذكي والذكاء الاصطناعي", "orientation-portrait-pro"),
            new FeatureReference(174, "المساعد الذكي والذكاء الاصطناعي", "productivity-reading-time"),
            new FeatureReference(175, "المساعد الذكي والذكاء الاصطناعي", "productivity-session-report"),
            new FeatureReference(176, "الهندسة الجدولية والحسابات", "table-calculation-template"),
            new FeatureReference(177, "الهندسة الجدولية والحسابات", "table-format-currency"),
            new FeatureReference(178, "الهندسة الجدولية والحسابات", "table-format-date"),
            new FeatureReference(179, "الهندسة الجدولية والحسابات", "table-alternate-columns"),
            new FeatureReference(180, "الهندسة الجدولية والحسابات", "table-format-percent"),
            new FeatureReference(181, "الهندسة الجدولية والحسابات", "table-summary-template"),
            new FeatureReference(182, "الهندسة الجدولية والحسابات", "tabs-to-table-smart"),
            new FeatureReference(183, "الهندسة الجدولية والحسابات", "table-sum-column"),
            new FeatureReference(184, "الهندسة الجدولية والحسابات", "table-average-column"),
            new FeatureReference(185, "الهندسة الجدولية والحسابات", "table-sort-asc"),
            new FeatureReference(186, "الهندسة الجدولية والحسابات", "table-sort-desc"),
            new FeatureReference(187, "الهندسة الجدولية والحسابات", "table-autofit-window"),
            new FeatureReference(188, "الهندسة الجدولية والحسابات", "table-banded-rows"),
            new FeatureReference(189, "الهندسة الجدولية والحسابات", "table-center-cells"),
            new FeatureReference(190, "الهندسة الجدولية والحسابات", "table-col-right"),
            new FeatureReference(191, "الهندسة الجدولية والحسابات", "table-number-first-column"),
            new FeatureReference(192, "الهندسة الجدولية والحسابات", "table-professional"),
            new FeatureReference(193, "الهندسة الجدولية والحسابات", "table-row-below"),
            new FeatureReference(194, "الهندسة الجدولية والحسابات", "table-transpose"),
            new FeatureReference(195, "الهندسة الجدولية والحسابات", "table-vertical-bottom"),
            new FeatureReference(196, "الهندسة الجدولية والحسابات", "table-vertical-middle"),
            new FeatureReference(197, "الهندسة الجدولية والحسابات", "table-vertical-top"),
            new FeatureReference(198, "الهندسة الجدولية والحسابات", "table-borders-all"),
            new FeatureReference(199, "الهندسة الجدولية والحسابات", "table-borders-none"),
            new FeatureReference(200, "الهندسة الجدولية والحسابات", "table-col-left"),
            new FeatureReference(201, "الهندسة الجدولية والحسابات", "table-delete-column"),
            new FeatureReference(202, "الهندسة الجدولية والحسابات", "table-delete-row"),
            new FeatureReference(203, "الهندسة الجدولية والحسابات", "table-distribute-rows"),
            new FeatureReference(204, "الهندسة الجدولية والحسابات", "table-header-style"),
            new FeatureReference(205, "الهندسة الجدولية والحسابات", "table-ltr"),
            new FeatureReference(206, "الهندسة الجدولية والحسابات", "table-merge-cells"),
            new FeatureReference(207, "الهندسة الجدولية والحسابات", "table-remove-duplicate-rows"),
            new FeatureReference(208, "الهندسة الجدولية والحسابات", "table-remove-empty-rows"),
            new FeatureReference(209, "الهندسة الجدولية والحسابات", "table-repeat-header"),
            new FeatureReference(210, "الهندسة الجدولية والحسابات", "table-row-above"),
            new FeatureReference(211, "الهندسة الجدولية والحسابات", "table-rtl"),
            new FeatureReference(212, "الهندسة الجدولية والحسابات", "table-split-cell"),
            new FeatureReference(213, "الهندسة الجدولية والحسابات", "table-to-text"),
            new FeatureReference(214, "الهندسة الجدولية والحسابات", "table-trim-cells"),
            new FeatureReference(215, "الهندسة الجدولية والحسابات", "text-to-table"),
            new FeatureReference(216, "الهندسة الجدولية والحسابات", "table-autofit-content"),
            new FeatureReference(217, "الهندسة الجدولية والحسابات", "table-digits-eastern-pro"),
            new FeatureReference(218, "الهندسة الجدولية والحسابات", "table-digits-western-pro"),
            new FeatureReference(219, "الهندسة الجدولية والحسابات", "table-distribute-columns"),
            new FeatureReference(220, "الهندسة الجدولية والحسابات", "table-auto-row-height"),
            new FeatureReference(221, "الميديا والوسائط والأشكال", "media-caption-images"),
            new FeatureReference(222, "الميديا والوسائط والأشكال", "media-accessibility-report"),
            new FeatureReference(223, "الميديا والوسائط والأشكال", "media-center-images"),
            new FeatureReference(224, "الميديا والوسائط والأشكال", "media-compress-pictures"),
            new FeatureReference(225, "الميديا والوسائط والأشكال", "media-export-images"),
            new FeatureReference(226, "الميديا والوسائط والأشكال", "media-fit-page"),
            new FeatureReference(227, "الميديا والوسائط والأشكال", "media-resize-half"),
            new FeatureReference(228, "الميديا والوسائط والأشكال", "insert-checkbox-symbols"),
            new FeatureReference(229, "الميديا والوسائط والأشكال", "insert-current-time"),
            new FeatureReference(230, "الميديا والوسائط والأشكال", "insert-document-info"),
            new FeatureReference(231, "الميديا والوسائط والأشكال", "insert-iso-date"),
            new FeatureReference(232, "الميديا والوسائط والأشكال", "insert-page-x-of-y"),
            new FeatureReference(233, "الميديا والوسائط والأشكال", "insert-timestamp"),
            new FeatureReference(234, "الميديا والوسائط والأشكال", "font-color-blue-pro"),
            new FeatureReference(235, "الميديا والوسائط والأشكال", "font-color-gray-pro"),
            new FeatureReference(236, "الميديا والوسائط والأشكال", "font-color-green-pro"),
            new FeatureReference(237, "الميديا والوسائط والأشكال", "font-color-red-pro"),
            new FeatureReference(238, "الميديا والوسائط والأشكال", "text-allcaps-off"),
            new FeatureReference(239, "الميديا والوسائط والأشكال", "text-allcaps-on"),
            new FeatureReference(240, "الميديا والوسائط والأشكال", "text-bold-off"),
            new FeatureReference(241, "الميديا والوسائط والأشكال", "text-bold-on"),
            new FeatureReference(242, "الميديا والوسائط والأشكال", "text-italic-off"),
            new FeatureReference(243, "الميديا والوسائط والأشكال", "text-italic-on"),
            new FeatureReference(244, "الميديا والوسائط والأشكال", "text-strike-off"),
            new FeatureReference(245, "الميديا والوسائط والأشكال", "text-strike-on"),
            new FeatureReference(246, "الميديا والوسائط والأشكال", "text-subscript"),
            new FeatureReference(247, "الميديا والوسائط والأشكال", "text-superscript"),
            new FeatureReference(248, "الميديا والوسائط والأشكال", "text-underline-off"),
            new FeatureReference(249, "الميديا والوسائط والأشكال", "text-underline-on"),
            new FeatureReference(250, "الميديا والوسائط والأشكال", "line-numbers-continuous-pro"),
            new FeatureReference(251, "الميديا والوسائط والأشكال", "clear-highlight-pro"),
            new FeatureReference(252, "الميديا والوسائط والأشكال", "font-color-automatic"),
            new FeatureReference(253, "الميديا والوسائط والأشكال", "highlight-clear"),
            new FeatureReference(254, "الميديا والوسائط والأشكال", "highlight-green"),
            new FeatureReference(255, "الميديا والوسائط والأشكال", "highlight-red"),
            new FeatureReference(256, "الميديا والوسائط والأشكال", "highlight-yellow"),
            new FeatureReference(257, "الميديا والوسائط والأشكال", "insert-issue-log-pro"),
            new FeatureReference(258, "الميديا والوسائط والأشكال", "insert-issue-register-v3"),
            new FeatureReference(259, "الميديا والوسائط والأشكال", "about"),
            new FeatureReference(260, "الميديا والوسائط والأشكال", "academic-bibliography-audit"),
            new FeatureReference(261, "أتمتة العمليات المجمعة", "batch-accept-revisions"),
            new FeatureReference(262, "أتمتة العمليات المجمعة", "batch-protect-readonly"),
            new FeatureReference(263, "أتمتة العمليات المجمعة", "batch-remove-comments"),
            new FeatureReference(264, "أتمتة العمليات المجمعة", "batch-remove-properties"),
            new FeatureReference(265, "أتمتة العمليات المجمعة", "batch-update-fields"),
            new FeatureReference(266, "أتمتة العمليات المجمعة", "batch-export-pdf-v4"),
            new FeatureReference(267, "أتمتة العمليات المجمعة", "batch-print-documents"),
            new FeatureReference(268, "أتمتة العمليات المجمعة", "batch-save-docx"),
            new FeatureReference(269, "أتمتة العمليات المجمعة", "batch-pdf"),
            new FeatureReference(270, "أتمتة العمليات المجمعة", "archive-package"),
            new FeatureReference(271, "أتمتة العمليات المجمعة", "open-document-folder"),
            new FeatureReference(272, "أتمتة العمليات المجمعة", "copy-as-markdown"),
            new FeatureReference(273, "أتمتة العمليات المجمعة", "copy-document-path"),
            new FeatureReference(274, "أتمتة العمليات المجمعة", "export-pdf"),
            new FeatureReference(275, "أتمتة العمليات المجمعة", "export-pdfa"),
            new FeatureReference(276, "أتمتة العمليات المجمعة", "export-plain-text"),
            new FeatureReference(277, "أتمتة العمليات المجمعة", "export-sections-pdf"),
            new FeatureReference(278, "أتمتة العمليات المجمعة", "export-selection-pdf"),
            new FeatureReference(279, "أتمتة العمليات المجمعة", "export-selection-text"),
            new FeatureReference(280, "أتمتة العمليات المجمعة", "merge-documents"),
            new FeatureReference(281, "أتمتة العمليات المجمعة", "move-selection-new-document"),
            new FeatureReference(282, "أتمتة العمليات المجمعة", "save-all"),
            new FeatureReference(283, "أتمتة العمليات المجمعة", "save-backup"),
            new FeatureReference(284, "أتمتة العمليات المجمعة", "save-docx-copy"),
            new FeatureReference(285, "أتمتة العمليات المجمعة", "save-version"),
            new FeatureReference(286, "أتمتة العمليات المجمعة", "lock-all-fields"),
            new FeatureReference(287, "أتمتة العمليات المجمعة", "remove-all-bookmarks-pro"),
            new FeatureReference(288, "أتمتة العمليات المجمعة", "toggle-field-codes"),
            new FeatureReference(289, "أتمتة العمليات المجمعة", "unlock-all-fields"),
            new FeatureReference(290, "أتمتة العمليات المجمعة", "prefix-folder-pro"),
            new FeatureReference(291, "أتمتة العمليات المجمعة", "academic-extract-citations"),
            new FeatureReference(292, "أتمتة العمليات المجمعة", "academic-footnote-audit"),
            new FeatureReference(293, "أتمتة العمليات المجمعة", "academic-insert-apa"),
            new FeatureReference(294, "أتمتة العمليات المجمعة", "academic-insert-mla"),
            new FeatureReference(295, "أتمتة العمليات المجمعة", "accept-revisions"),
            new FeatureReference(296, "أتمتة العمليات المجمعة", "activate"),
            new FeatureReference(297, "أتمتة العمليات المجمعة", "align-center"),
            new FeatureReference(298, "أتمتة العمليات المجمعة", "align-justify"),
            new FeatureReference(299, "أتمتة العمليات المجمعة", "align-left"),
            new FeatureReference(300, "أتمتة العمليات المجمعة", "align-right"),
            new FeatureReference(301, "البحث العلمي والمراجع", "reference-case"),
            new FeatureReference(302, "البحث العلمي والمراجع", "reference-doc"),
            new FeatureReference(303, "البحث العلمي والمراجع", "reference-memo"),
            new FeatureReference(304, "البحث العلمي والمراجع", "reference-rpt"),
            new FeatureReference(305, "البحث العلمي والمراجع", "time-reference"),
            new FeatureReference(306, "البحث العلمي والمراجع", "date-arabic-full"),
            new FeatureReference(307, "البحث العلمي والمراجع", "date-arabic-long"),
            new FeatureReference(308, "البحث العلمي والمراجع", "date-compact"),
            new FeatureReference(309, "البحث العلمي والمراجع", "date-day-month-year"),
            new FeatureReference(310, "البحث العلمي والمراجع", "date-english-short"),
            new FeatureReference(311, "البحث العلمي والمراجع", "date-iso"),
            new FeatureReference(312, "البحث العلمي والمراجع", "date-month-year"),
            new FeatureReference(313, "البحث العلمي والمراجع", "date-simple"),
            new FeatureReference(314, "البحث العلمي والمراجع", "date-slash-iso"),
            new FeatureReference(315, "البحث العلمي والمراجع", "date-us"),
            new FeatureReference(316, "البحث العلمي والمراجع", "time-12-seconds"),
            new FeatureReference(317, "البحث العلمي والمراجع", "time-12-short"),
            new FeatureReference(318, "البحث العلمي والمراجع", "time-24-seconds"),
            new FeatureReference(319, "البحث العلمي والمراجع", "time-24-short"),
            new FeatureReference(320, "البحث العلمي والمراجع", "time-compact"),
            new FeatureReference(321, "البحث العلمي والمراجع", "format-academic"),
            new FeatureReference(322, "البحث العلمي والمراجع", "catalog-600-center"),
            new FeatureReference(323, "البحث العلمي والمراجع", "command-center"),
            new FeatureReference(324, "البحث العلمي والمراجع", "find-replace-prompt"),
            new FeatureReference(325, "البحث العلمي والمراجع", "insert-toc"),
            new FeatureReference(326, "البحث العلمي والمراجع", "margins-academic-pro"),
            new FeatureReference(327, "البحث العلمي والمراجع", "remove-bookmarks"),
            new FeatureReference(328, "البحث العلمي والمراجع", "security-remove-hidden-text"),
            new FeatureReference(329, "البحث العلمي والمراجع", "template-tor"),
            new FeatureReference(330, "البحث العلمي والمراجع", "border-box"),
            new FeatureReference(331, "البحث العلمي والمراجع", "border-clear"),
            new FeatureReference(332, "البحث العلمي والمراجع", "clean-properties"),
            new FeatureReference(333, "البحث العلمي والمراجع", "clear-formatting"),
            new FeatureReference(334, "البحث العلمي والمراجع", "clipboard-append-collection"),
            new FeatureReference(335, "البحث العلمي والمراجع", "clipboard-clear-snippets"),
            new FeatureReference(336, "البحث العلمي والمراجع", "clipboard-insert-snippet"),
            new FeatureReference(337, "البحث العلمي والمراجع", "clipboard-save-snippet"),
            new FeatureReference(338, "البحث العلمي والمراجع", "columns-1-pro"),
            new FeatureReference(339, "البحث العلمي والمراجع", "columns-2-pro"),
            new FeatureReference(340, "البحث العلمي والمراجع", "columns-3-pro"),
            new FeatureReference(341, "الأمان والتشفير والطمس", "security-document-audit"),
            new FeatureReference(342, "الأمان والتشفير والطمس", "security-redact-emails"),
            new FeatureReference(343, "الأمان والتشفير والطمس", "security-redact-identifiers"),
            new FeatureReference(344, "الأمان والتشفير والطمس", "security-redact-phones"),
            new FeatureReference(345, "الأمان والتشفير والطمس", "security-redact-selection"),
            new FeatureReference(346, "الأمان والتشفير والطمس", "protect-forms"),
            new FeatureReference(347, "الأمان والتشفير والطمس", "protect-readonly"),
            new FeatureReference(348, "الأمان والتشفير والطمس", "remove-external-links"),
            new FeatureReference(349, "الأمان والتشفير والطمس", "remove-metadata"),
            new FeatureReference(350, "الأمان والتشفير والطمس", "unprotect"),
            new FeatureReference(351, "الأمان والتشفير والطمس", "workflow-final-share"),
            new FeatureReference(352, "الأمان والتشفير والطمس", "comments-report-pro"),
            new FeatureReference(353, "الأمان والتشفير والطمس", "reject-revisions"),
            new FeatureReference(354, "الأمان والتشفير والطمس", "remove-comments"),
            new FeatureReference(355, "الأمان والتشفير والطمس", "remove-endnotes"),
            new FeatureReference(356, "الأمان والتشفير والطمس", "remove-footnotes"),
            new FeatureReference(357, "الأمان والتشفير والطمس", "revisions-summary-pro"),
            new FeatureReference(358, "الأمان والتشفير والطمس", "track-off"),
            new FeatureReference(359, "الأمان والتشفير والطمس", "track-on"),
            new FeatureReference(360, "الأمان والتشفير والطمس", "unlink-selection-fields"),
            new FeatureReference(361, "الأمان والتشفير والطمس", "workflow-final-delivery"),
            new FeatureReference(362, "الأمان والتشفير والطمس", "form-export-controls-csv"),
            new FeatureReference(363, "الأمان والتشفير والطمس", "legal-party-table"),
            new FeatureReference(364, "الأمان والتشفير والطمس", "remove-hidden-text"),
            new FeatureReference(365, "الأمان والتشفير والطمس", "comma-list-bullets"),
            new FeatureReference(366, "الأمان والتشفير والطمس", "export-filtered-html"),
            new FeatureReference(367, "الأمان والتشفير والطمس", "export-odt"),
            new FeatureReference(368, "الأمان والتشفير والطمس", "export-pdf-page-range"),
            new FeatureReference(369, "الأمان والتشفير والطمس", "export-rtf"),
            new FeatureReference(370, "الأمان والتشفير والطمس", "extract-hashtags"),
            new FeatureReference(371, "الأمان والتشفير والطمس", "extract-mentions"),
            new FeatureReference(372, "الأمان والتشفير والطمس", "extract-numbers"),
            new FeatureReference(373, "الأمان والتشفير والطمس", "filter-keep-alphanumeric-pro"),
            new FeatureReference(374, "الأمان والتشفير والطمس", "filter-keep-digits-pro"),
            new FeatureReference(375, "الأمان والتشفير والطمس", "filter-keep-letters-pro"),
            new FeatureReference(376, "الطباعة والتصدير المتقدم", "print-booklet-layout"),
            new FeatureReference(377, "الطباعة والتصدير المتقدم", "margins-0-75cm"),
            new FeatureReference(378, "الطباعة والتصدير المتقدم", "margins-1-5cm"),
            new FeatureReference(379, "الطباعة والتصدير المتقدم", "margins-1cm"),
            new FeatureReference(380, "الطباعة والتصدير المتقدم", "margins-2-5cm"),
            new FeatureReference(381, "الطباعة والتصدير المتقدم", "margins-2cm"),
            new FeatureReference(382, "الطباعة والتصدير المتقدم", "margins-3cm"),
            new FeatureReference(383, "الطباعة والتصدير المتقدم", "margins-binding-pro"),
            new FeatureReference(384, "الطباعة والتصدير المتقدم", "margins-official-pro"),
            new FeatureReference(385, "الطباعة والتصدير المتقدم", "orientation-landscape-pro"),
            new FeatureReference(386, "الطباعة والتصدير المتقدم", "paper-a3-pro"),
            new FeatureReference(387, "الطباعة والتصدير المتقدم", "paper-a4-pro"),
            new FeatureReference(388, "الطباعة والتصدير المتقدم", "paper-a5-pro"),
            new FeatureReference(389, "الطباعة والتصدير المتقدم", "paper-legal-pro"),
            new FeatureReference(390, "الطباعة والتصدير المتقدم", "paper-letter-pro"),
            new FeatureReference(391, "الطباعة والتصدير المتقدم", "footer-text"),
            new FeatureReference(392, "الطباعة والتصدير المتقدم", "format-official-letter"),
            new FeatureReference(393, "الطباعة والتصدير المتقدم", "header-text"),
            new FeatureReference(394, "الطباعة والتصدير المتقدم", "insert-page-break"),
            new FeatureReference(395, "الطباعة والتصدير المتقدم", "insert-section-next"),
            new FeatureReference(396, "الطباعة والتصدير المتقدم", "keep-lines-together"),
            new FeatureReference(397, "الطباعة والتصدير المتقدم", "keep-with-next"),
            new FeatureReference(398, "الطباعة والتصدير المتقدم", "margins-narrow"),
            new FeatureReference(399, "الطباعة والتصدير المتقدم", "margins-normal"),
            new FeatureReference(400, "الطباعة والتصدير المتقدم", "page-a3"),
            new FeatureReference(401, "الطباعة والتصدير المتقدم", "page-a4"),
            new FeatureReference(402, "الطباعة والتصدير المتقدم", "page-break-before"),
            new FeatureReference(403, "الطباعة والتصدير المتقدم", "page-landscape"),
            new FeatureReference(404, "الطباعة والتصدير المتقدم", "page-letter"),
            new FeatureReference(405, "الطباعة والتصدير المتقدم", "page-numbers-add"),
            new FeatureReference(406, "الطباعة والتصدير المتقدم", "page-numbers-remove"),
            new FeatureReference(407, "الطباعة والتصدير المتقدم", "page-portrait"),
            new FeatureReference(408, "الطباعة والتصدير المتقدم", "filter-remove-arabic-pro"),
            new FeatureReference(409, "الطباعة والتصدير المتقدم", "filter-remove-brackets-pro"),
            new FeatureReference(410, "الطباعة والتصدير المتقدم", "filter-remove-digits-pro"),
            new FeatureReference(411, "الحافظة والأتمتة والاختصارات", "prefix-arrow-pro"),
            new FeatureReference(412, "الحافظة والأتمتة والاختصارات", "prefix-bullet-pro"),
            new FeatureReference(413, "الحافظة والأتمتة والاختصارات", "prefix-calendar-pro"),
            new FeatureReference(414, "الحافظة والأتمتة والاختصارات", "prefix-check-done-pro"),
            new FeatureReference(415, "الحافظة والأتمتة والاختصارات", "prefix-check-empty-pro"),
            new FeatureReference(416, "الحافظة والأتمتة والاختصارات", "prefix-circle-pro"),
            new FeatureReference(417, "الحافظة والأتمتة والاختصارات", "prefix-clock-pro"),
            new FeatureReference(418, "الحافظة والأتمتة والاختصارات", "prefix-dash-pro"),
            new FeatureReference(419, "الحافظة والأتمتة والاختصارات", "prefix-email-pro"),
            new FeatureReference(420, "الحافظة والأتمتة والاختصارات", "prefix-file-pro"),
            new FeatureReference(421, "الحافظة والأتمتة والاختصارات", "prefix-flag-pro"),
            new FeatureReference(422, "الحافظة والأتمتة والاختصارات", "prefix-info-pro"),
            new FeatureReference(423, "الحافظة والأتمتة والاختصارات", "prefix-link-pro"),
            new FeatureReference(424, "الحافظة والأتمتة والاختصارات", "prefix-phone-pro"),
            new FeatureReference(425, "الحافظة والأتمتة والاختصارات", "prefix-pin-pro"),
            new FeatureReference(426, "الحافظة والأتمتة والاختصارات", "prefix-square-pro"),
            new FeatureReference(427, "الحافظة والأتمتة والاختصارات", "prefix-star-pro"),
            new FeatureReference(428, "الحافظة والأتمتة والاختصارات", "prefix-user-pro"),
            new FeatureReference(429, "الحافظة والأتمتة والاختصارات", "prefix-warning-pro"),
            new FeatureReference(430, "الحافظة والأتمتة والاختصارات", "form-date-control"),
            new FeatureReference(431, "الحافظة والأتمتة والاختصارات", "form-text-control"),
            new FeatureReference(432, "الحافظة والأتمتة والاختصارات", "form-checkbox-control"),
            new FeatureReference(433, "الحافظة والأتمتة والاختصارات", "insert-action-log-v3"),
            new FeatureReference(434, "الحافظة والأتمتة والاختصارات", "insert-action-tracker-pro"),
            new FeatureReference(435, "الحافظة والأتمتة والاختصارات", "insert-approval-table-pro"),
            new FeatureReference(436, "الحافظة والأتمتة والاختصارات", "insert-asset-register"),
            new FeatureReference(437, "الحافظة والأتمتة والاختصارات", "insert-attendance-sheet-v3"),
            new FeatureReference(438, "الحافظة والأتمتة والاختصارات", "insert-audit-findings"),
            new FeatureReference(439, "الحافظة والأتمتة والاختصارات", "insert-budget-table"),
            new FeatureReference(440, "الحافظة والأتمتة والاختصارات", "insert-budget-tracker"),
            new FeatureReference(441, "الحافظة والأتمتة والاختصارات", "insert-change-request"),
            new FeatureReference(442, "الحافظة والأتمتة والاختصارات", "insert-communication-plan"),
            new FeatureReference(443, "الحافظة والأتمتة والاختصارات", "insert-contact-directory-pro"),
            new FeatureReference(444, "الحافظة والأتمتة والاختصارات", "insert-contract-tracker"),
            new FeatureReference(445, "الحافظة والأتمتة والاختصارات", "insert-date-time"),
            new FeatureReference(446, "التدقيق القانوني والعقود", "legal-clause-checklist"),
            new FeatureReference(447, "التدقيق القانوني والعقود", "legal-highlight-dates"),
            new FeatureReference(448, "التدقيق القانوني والعقود", "insert-decision-log"),
            new FeatureReference(449, "التدقيق القانوني والعقود", "insert-distribution-list-pro"),
            new FeatureReference(450, "التدقيق القانوني والعقود", "insert-document-control"),
            new FeatureReference(451, "التدقيق القانوني والعقود", "insert-inventory-table-pro"),
            new FeatureReference(452, "التدقيق القانوني والعقود", "insert-kpi-table"),
            new FeatureReference(453, "التدقيق القانوني والعقود", "insert-raci-matrix"),
            new FeatureReference(454, "التدقيق القانوني والعقود", "insert-risk-register-pro"),
            new FeatureReference(455, "التدقيق القانوني والعقود", "insert-timeline-table"),
            new FeatureReference(456, "التدقيق القانوني والعقود", "insert-yes-no-table"),
            new FeatureReference(457, "التدقيق القانوني والعقود", "insert-decision-log-v3"),
            new FeatureReference(458, "التدقيق القانوني والعقود", "insert-document-register-v3"),
            new FeatureReference(459, "التدقيق القانوني والعقود", "insert-donor-results"),
            new FeatureReference(460, "التدقيق القانوني والعقود", "insert-incident-register"),
            new FeatureReference(461, "التدقيق القانوني والعقود", "insert-inventory-register-v3"),
            new FeatureReference(462, "التدقيق القانوني والعقود", "insert-kpi-dashboard"),
            new FeatureReference(463, "التدقيق القانوني والعقود", "insert-leave-tracker"),
            new FeatureReference(464, "التدقيق القانوني والعقود", "insert-lessons-learned"),
            new FeatureReference(465, "التدقيق القانوني والعقود", "insert-medical-triage"),
            new FeatureReference(466, "التدقيق القانوني والعقود", "insert-meeting-agenda"),
            new FeatureReference(467, "التدقيق القانوني والعقود", "insert-meeting-minutes"),
            new FeatureReference(468, "التدقيق القانوني والعقود", "insert-milestone-register"),
            new FeatureReference(469, "التدقيق القانوني والعقود", "insert-procurement-plan"),
            new FeatureReference(470, "التدقيق القانوني والعقود", "insert-project-timeline"),
            new FeatureReference(471, "التدقيق القانوني والعقود", "insert-quality-checklist"),
            new FeatureReference(472, "التدقيق القانوني والعقود", "insert-raci-matrix-v3"),
            new FeatureReference(473, "التدقيق القانوني والعقود", "insert-risk-register-v3"),
            new FeatureReference(474, "التدقيق القانوني والعقود", "insert-stakeholder-register"),
            new FeatureReference(475, "التدقيق القانوني والعقود", "insert-training-matrix"),
            new FeatureReference(476, "التدقيق القانوني والعقود", "filter-remove-latin-pro"),
            new FeatureReference(477, "التدقيق القانوني والعقود", "filter-slashes-to-dashes-pro"),
            new FeatureReference(478, "التدقيق القانوني والعقود", "font-arial-14"),
            new FeatureReference(479, "التدقيق القانوني والعقود", "font-calibri-11"),
            new FeatureReference(480, "التدقيق القانوني والعقود", "font-tahoma-12"),
            new FeatureReference(481, "إدارة المشاريع والمهام", "project-weekly-status"),
            new FeatureReference(482, "إدارة المشاريع والمهام", "project-deliverables-register"),
            new FeatureReference(483, "إدارة المشاريع والمهام", "project-gantt-table"),
            new FeatureReference(484, "إدارة المشاريع والمهام", "project-task-board"),
            new FeatureReference(485, "إدارة المشاريع والمهام", "template-concept-note"),
            new FeatureReference(486, "إدارة المشاريع والمهام", "template-project-report"),
            new FeatureReference(487, "إدارة المشاريع والمهام", "template-risk-register"),
            new FeatureReference(488, "إدارة المشاريع والمهام", "template-sop"),
            new FeatureReference(489, "إدارة المشاريع والمهام", "template-action-plan"),
            new FeatureReference(490, "إدارة المشاريع والمهام", "template-agenda"),
            new FeatureReference(491, "إدارة المشاريع والمهام", "template-attendance"),
            new FeatureReference(492, "إدارة المشاريع والمهام", "template-certificate"),
            new FeatureReference(493, "إدارة المشاريع والمهام", "template-cover-letter"),
            new FeatureReference(494, "إدارة المشاريع والمهام", "template-donor-report"),
            new FeatureReference(495, "إدارة المشاريع والمهام", "template-handover"),
            new FeatureReference(496, "إدارة المشاريع والمهام", "template-invoice"),
            new FeatureReference(497, "إدارة المشاريع والمهام", "template-medical-report"),
            new FeatureReference(498, "إدارة المشاريع والمهام", "template-memo"),
            new FeatureReference(499, "إدارة المشاريع والمهام", "template-minutes"),
            new FeatureReference(500, "إدارة المشاريع والمهام", "template-official-letter"),
            new FeatureReference(501, "إدارة المشاريع والمهام", "template-quotation"),
            new FeatureReference(502, "إدارة المشاريع والمهام", "font-tahoma-14"),
            new FeatureReference(503, "إدارة المشاريع والمهام", "font-times-11"),
            new FeatureReference(504, "إدارة المشاريع والمهام", "font-times-12"),
            new FeatureReference(505, "إدارة المشاريع والمهام", "font-times-14"),
            new FeatureReference(506, "إدارة المشاريع والمهام", "font-traditional-arabic-16"),
            new FeatureReference(507, "إدارة المشاريع والمهام", "font-trebuchet-11"),
            new FeatureReference(508, "إدارة المشاريع والمهام", "font-verdana-10"),
            new FeatureReference(509, "إدارة المشاريع والمهام", "format-apply"),
            new FeatureReference(510, "إدارة المشاريع والمهام", "format-arabic-report"),
            new FeatureReference(511, "إدارة المشاريع والمهام", "format-copy"),
            new FeatureReference(512, "إدارة المشاريع والمهام", "hanging-indent"),
            new FeatureReference(513, "إدارة المشاريع والمهام", "heading-1"),
            new FeatureReference(514, "إدارة المشاريع والمهام", "heading-2"),
            new FeatureReference(515, "إدارة المشاريع والمهام", "heading-3"),
            new FeatureReference(516, "إدارة المشاريع والمهام", "health-check"),
            new FeatureReference(517, "إدارة المشاريع والمهام", "highlight-term"),
            new FeatureReference(518, "إدارة المشاريع والمهام", "indent-first-0-5cm"),
            new FeatureReference(519, "إدارة المشاريع والمهام", "indent-first-1cm"),
            new FeatureReference(520, "إدارة المشاريع والمهام", "indent-first-line"),
            new FeatureReference(521, "إدارة النماذج وإدخال البيانات", "indent-hanging-0-5cm"),
            new FeatureReference(522, "إدارة النماذج وإدخال البيانات", "indent-hanging-1cm"),
            new FeatureReference(523, "إدارة النماذج وإدخال البيانات", "indent-left-0-5cm"),
            new FeatureReference(524, "إدارة النماذج وإدخال البيانات", "indent-left-1cm"),
            new FeatureReference(525, "إدارة النماذج وإدخال البيانات", "indent-remove"),
            new FeatureReference(526, "إدارة النماذج وإدخال البيانات", "indent-right-0-5cm"),
            new FeatureReference(527, "إدارة النماذج وإدخال البيانات", "indent-right-1cm"),
            new FeatureReference(528, "إدارة النماذج وإدخال البيانات", "insert-section-continuous"),
            new FeatureReference(529, "إدارة النماذج وإدخال البيانات", "insert-signature"),
            new FeatureReference(530, "إدارة النماذج وإدخال البيانات", "license-info"),
            new FeatureReference(531, "إدارة النماذج وإدخال البيانات", "line-exact-12"),
            new FeatureReference(532, "إدارة النماذج وإدخال البيانات", "line-exact-14"),
            new FeatureReference(533, "إدارة النماذج وإدخال البيانات", "line-exact-16"),
            new FeatureReference(534, "إدارة النماذج وإدخال البيانات", "line-exact-18"),
            new FeatureReference(535, "إدارة النماذج وإدخال البيانات", "line-numbers-off"),
            new FeatureReference(536, "إدارة النماذج وإدخال البيانات", "line-numbers-on"),
            new FeatureReference(537, "إدارة النماذج وإدخال البيانات", "line-spacing-1"),
            new FeatureReference(538, "إدارة النماذج وإدخال البيانات", "line-spacing-115"),
            new FeatureReference(539, "إدارة النماذج وإدخال البيانات", "line-spacing-15"),
            new FeatureReference(540, "إدارة النماذج وإدخال البيانات", "line-spacing-2"),
            new FeatureReference(541, "إدارة النماذج وإدخال البيانات", "machine-id"),
            new FeatureReference(542, "إدارة النماذج وإدخال البيانات", "normalize-unicode-spaces"),
            new FeatureReference(543, "إدارة النماذج وإدخال البيانات", "paragraph-after-0-pro"),
            new FeatureReference(544, "إدارة النماذج وإدخال البيانات", "paragraph-after-12-pro"),
            new FeatureReference(545, "إدارة النماذج وإدخال البيانات", "paragraph-after-3-pro"),
            new FeatureReference(546, "إدارة النماذج وإدخال البيانات", "paragraph-after-6-pro"),
            new FeatureReference(547, "إدارة النماذج وإدخال البيانات", "paragraph-before-0"),
            new FeatureReference(548, "إدارة النماذج وإدخال البيانات", "paragraph-before-12"),
            new FeatureReference(549, "إدارة النماذج وإدخال البيانات", "paragraph-before-3"),
            new FeatureReference(550, "إدارة النماذج وإدخال البيانات", "paragraph-before-6"),
            new FeatureReference(551, "إدارة النماذج وإدخال البيانات", "paragraphs-checkboxes"),
            new FeatureReference(552, "إدارة النماذج وإدخال البيانات", "paragraphs-checked"),
            new FeatureReference(553, "إدارة النماذج وإدخال البيانات", "paragraphs-semicolon-list"),
            new FeatureReference(554, "إدارة النماذج وإدخال البيانات", "productivity-focus-mode"),
            new FeatureReference(555, "إدارة النماذج وإدخال البيانات", "productivity-restore-view"),
            new FeatureReference(556, "إدارة النماذج وإدخال البيانات", "productivity-word-goal"),
            new FeatureReference(557, "إدارة النماذج وإدخال البيانات", "productivity-writing-session"),
            new FeatureReference(558, "إدارة النماذج وإدخال البيانات", "proofing-language-arabic"),
            new FeatureReference(559, "إدارة النماذج وإدخال البيانات", "proofing-language-english"),
            new FeatureReference(560, "إدارة النماذج وإدخال البيانات", "remove-all-blank-paragraphs"),
            new FeatureReference(561, "التخصيص والأداء والإنتاجية", "table-column-width-prompt"),
            new FeatureReference(562, "التخصيص والأداء والإنتاجية", "titlecase"),
            new FeatureReference(563, "التخصيص والأداء والإنتاجية", "remove-page-breaks"),
            new FeatureReference(564, "التخصيص والأداء والإنتاجية", "remove-repeated-punctuation"),
            new FeatureReference(565, "التخصيص والأداء والإنتاجية", "remove-section-breaks"),
            new FeatureReference(566, "التخصيص والأداء والإنتاجية", "remove-short-paragraphs"),
            new FeatureReference(567, "التخصيص والأداء والإنتاجية", "reverse-paragraph-order"),
            new FeatureReference(568, "التخصيص والأداء والإنتاجية", "sentences-to-paragraphs"),
            new FeatureReference(569, "التخصيص والأداء والإنتاجية", "sort-paragraphs-length"),
            new FeatureReference(570, "التخصيص والأداء والإنتاجية", "space-after-0"),
            new FeatureReference(571, "التخصيص والأداء والإنتاجية", "space-after-12"),
            new FeatureReference(572, "التخصيص والأداء والإنتاجية", "space-after-6"),
            new FeatureReference(573, "التخصيص والأداء والإنتاجية", "strip-html-tags"),
            new FeatureReference(574, "التخصيص والأداء والإنتاجية", "strip-list-markers"),
            new FeatureReference(575, "التخصيص والأداء والإنتاجية", "style-normal"),
            new FeatureReference(576, "التخصيص والأداء والإنتاجية", "table-bold-first-row"),
            new FeatureReference(577, "التخصيص والأداء والإنتاجية", "table-currency-format"),
            new FeatureReference(578, "التخصيص والأداء والإنتاجية", "table-percentage-format"),
            new FeatureReference(579, "التخصيص والأداء والإنتاجية", "table-remove-cell-breaks"),
            new FeatureReference(580, "التخصيص والأداء والإنتاجية", "tabs-to-spaces"),
            new FeatureReference(581, "التخصيص والأداء والإنتاجية", "unique-sorted-lines"),
            new FeatureReference(582, "التخصيص والأداء والإنتاجية", "unique-words-only"),
            new FeatureReference(583, "التخصيص والأداء والإنتاجية", "unlink-fields"),
            new FeatureReference(584, "التخصيص والأداء والإنتاجية", "update-fields"),
            new FeatureReference(585, "التخصيص والأداء والإنتاجية", "widow-control-on"),
            new FeatureReference(586, "التخصيص والأداء والإنتاجية", "wrap-angles-pro"),
            new FeatureReference(587, "التخصيص والأداء والإنتاجية", "wrap-arabic-brackets-pro"),
            new FeatureReference(588, "التخصيص والأداء والإنتاجية", "wrap-arabic-quotes"),
            new FeatureReference(589, "التخصيص والأداء والإنتاجية", "wrap-arabic-quotes-pro"),
            new FeatureReference(590, "التخصيص والأداء والإنتاجية", "wrap-braces-pro"),
            new FeatureReference(591, "التخصيص والأداء والإنتاجية", "wrap-brackets"),
            new FeatureReference(592, "التخصيص والأداء والإنتاجية", "wrap-brackets-pro"),
            new FeatureReference(593, "التخصيص والأداء والإنتاجية", "wrap-double-parentheses-pro"),
            new FeatureReference(594, "التخصيص والأداء والإنتاجية", "wrap-parentheses"),
            new FeatureReference(595, "التخصيص والأداء والإنتاجية", "wrap-parentheses-pro"),
            new FeatureReference(596, "التخصيص والأداء والإنتاجية", "wrap-pipes-pro"),
            new FeatureReference(597, "التخصيص والأداء والإنتاجية", "wrap-slashes-pro"),
            new FeatureReference(598, "التخصيص والأداء والإنتاجية", "wrap-smart-double-pro"),
            new FeatureReference(599, "التخصيص والأداء والإنتاجية", "wrap-smart-single-pro"),
            new FeatureReference(600, "التخصيص والأداء والإنتاجية", "wrap-underscores-pro"),
        };
    }
}